server:
  port: 9000
spring:
  application:
    name: ad-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

zuul:
  prefix: /ad
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      strip-prefix: false